### ISSUE TITLE
dev not working

### ISSUE THREAD

**Issue by RufusK** [netlify-templates/kpop-stack#49] opened 2022-05-20 10:31 UTC
I love the idea of this template. Deployment on netlify and integration with supabase worked like a charm, but I can't get the dev environment to work.

After following all the steps in the readme (creating the project with the "deploy to netlify" button), running "npm run dev" only gives me "Function not found..." in http://localhost:3000/

Logs look like this:
![image](https://user-images.githubusercontent.com/11466451/169509185-20afdaf2-d6d9-40dc-a6c1-8ab8d529bf1c.png)

I havent changed any files, the only generated file is the .netlify/state.json

If I run npm run build it creates files in public/build and .netlify/functions-internal/server.js.
If I then run npm run dev, it serves the site correctly but after changing files it doesn't reflect those changes but apparently still serves the files generated in npm run build.

**Comment by maxcell** [comment] 2022-05-20 13:06
Thank you for this report! I think we will need to modify the README to include this manual build step so you get the generated server files.

It still is perplexing to me that after building manually you're seeing files changed but the website isn't reflecting those changes 🤔. That step I cannot reproduce myself, it still automatically reloads and shows the changes. Do they appear for you at all with a manual refresh of the browser at all? Could you also share your node & package manager version?

**Comment by kasperstorgaard** [comment] 2022-05-20 19:42
I can't even get that far, the server "hangs" on netlify dev, and when I kill that process the localhost:3000 message appears.
This is after following the guide of building first.

`npm run dev`
<img width="564" alt="Screenshot 2022-05-20 at 21 37 45" src="https://user-images.githubusercontent.com/3033516/169600058-54e9540e-3d1b-4722-bb2c-5a4457d95ddc.png">

after killing process
<img width="523" alt="Screenshot 2022-05-20 at 21 37 53" src="https://user-images.githubusercontent.com/3033516/169600050-db337733-e686-485b-8cd3-eeac1d3b83d9.png">


node version: 16.4.2

**Comment by RufusK** [comment] 2022-05-20 21:29
node: 16.14.4 
npm:8.5.0

Thanks for your quick reply.
Apparently it doesnt run the command specified in netlify.toml:
[dev]
  command = "remix watch"
  port = 3000
When i run remix watch myself in a separate terminal, everything works fine. (even without running 'npm run build' before)

**Comment by maxcell** [comment] 2022-05-26 20:11
@RufusK That's also very interesting that it isn't running. What version of the netlify-cli are you using?

**Comment by kasperstorgaard** [comment] 2022-05-27 11:31
> > This is after following the guide of building first.
> 
> Similar @kasperstorgaard what version of the Netlify CLI are you using?

I actually got it working, not sure what the issue was, could have been my own mistake.

**Comment by RufusK** [comment] 2022-05-28 19:59
when i run netlify -v:
netlify-cli/6.7.1 win32-x64 node-v16.14.2

**Comment by leofmoura** [comment] 2022-06-05 17:19
I can't make it work too. What am I missing here?

node --version:  v18.1.0

Running: npm run dev

<img width="1521" alt="image" src="https://user-images.githubusercontent.com/3877117/172062336-adf72662-a9b5-4c54-bea2-5198de6366c9.png">


Getting this issue when creating a user:
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/3877117/172062292-1f7ea910-2005-4ec2-800f-f9c6428943eb.png">

**Comment by maxcell** [comment] 2022-06-06 12:43
Howdy @leofmoura I think your issue may be separate so I've opened up #50 to further that dialog there.

**Comment by maxcell** [comment] 2022-07-18 20:01
I think we're coming to a head with this problem and gonna try to work on this with #56

**Comment by maxcell** [comment] 2022-08-02 17:26
This should be complete now that #56 is merged. You will be able to use `npm run dev` and get hot reloading! If you want to examine and test Netlify features such as redirects or functions, you can run `ntl dev`

**Closed by maxcell** 2022-08-02 17:26 UTC
